# Generated by Django 6.0 on 2025-12-26 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=30)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DermaAIapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=30)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DermaAIapp.login')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DermaAIapp.hospital')),
            ],
        ),
    ]
