# Generated by Django 6.0 on 2025-12-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0002_hospital_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
    ]
