# Generated by Django 6.0 on 2025-12-27 05:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0004_doctor_city_doctor_district_doctor_hospital_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='login_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='login',
            name='user_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
