# Generated by Django 6.0 on 2025-12-27 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0005_login_login_status_login_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('current_date', models.DateField(auto_now_add=True)),
                ('prescription', models.TextField(max_length=500)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DermaAIapp.doctor')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='DermaAIapp.user')),
            ],
        ),
    ]
