# Generated by Django 6.0 on 2025-12-30 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0006_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=200)),
                ('cardno', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('expiry', models.CharField(max_length=20)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('Appointmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DermaAIapp.appointment')),
            ],
        ),
    ]
