# Generated by Django 6.0 on 2025-12-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Payment_status',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
