# Generated by Django 6.0 on 2025-12-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0008_appointment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Payment_status',
            field=models.IntegerField(default=0),
        ),
    ]
