# Generated by Django 6.0 on 2025-12-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0009_alter_appointment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.CharField(max_length=4),
        ),
    ]
