# Generated by Django 6.0 on 2025-12-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0010_alter_payment_cardno_alter_payment_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultationfee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
