# Generated by Django 6.0 on 2025-12-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0011_doctor_consultationfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultationfee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
