# Generated by Django 6.0 on 2025-12-31 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0013_payment_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(max_length=500)),
                ('current_date', models.DateField(auto_now=True)),
                ('reply', models.TextField(blank=True, max_length=500, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DermaAIapp.user')),
            ],
        ),
    ]
