# Generated by Django 6.0 on 2026-01-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0015_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
