# Generated by Django 6.0 on 2026-01-10 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0016_appointment_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DermaAIapp.login')),
            ],
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
