# Generated by Django 6.0 on 2026-01-10 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0017_hospitalreg_delete_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catageory', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('vechile_number', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DermaAIapp.login')),
            ],
        ),
    ]
