# Generated by Django 6.0 on 2026-01-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0018_ambulance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='hospital_name',
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='vechile_number',
            field=models.CharField(max_length=10),
        ),
    ]
