# Generated by Django 6.0 on 2026-01-10 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0019_remove_ambulance_hospital_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DermaAIapp.hospitalreg'),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='loginid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DermaAIapp.login'),
        ),
    ]
