# Generated by Django 6.0 on 2026-01-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0020_ambulance_hospital_alter_ambulance_loginid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalreg',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
