# Generated by Django 6.0 on 2026-01-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0021_hospitalreg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
