# Generated by Django 6.0 on 2026-01-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0022_ambulance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='hospitalreg',
            name='status',
        ),
    ]
