# Generated by Django 6.0 on 2026-01-15 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0023_remove_ambulance_status_remove_hospitalreg_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=100)),
                ('Time', models.CharField(max_length=100)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('Ambulance_loginid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DermaAIapp.ambulance')),
                ('user_loginid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DermaAIapp.user')),
            ],
        ),
    ]
