# Generated by Django 6.0 on 2026-01-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0024_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='assign',
            name='Time',
        ),
    ]
