# Generated by Django 6.0 on 2026-01-15 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0025_remove_assign_date_remove_assign_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='assign_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assign',
            name='assign_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
