# Generated by Django 6.0 on 2026-01-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0026_assign_assign_date_assign_assign_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
