# Generated by Django 6.0 on 2026-01-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0028_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='reply',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
