# Generated by Django 6.0 on 2026-01-19 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0029_chat_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField()),
                ('current_date', models.DateField(auto_now=True)),
                ('Appointmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DermaAIapp.appointment')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DermaAIapp.doctor')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DermaAIapp.user')),
            ],
        ),
    ]
