# Generated by Django 6.0 on 2026-01-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0030_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='test_reports/'),
        ),
    ]
