# Generated by Django 6.0 on 2026-01-22 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0031_test_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='h_loginid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DermaAIapp.hospitalreg'),
        ),
    ]
