# Generated by Django 6.0 on 2026-01-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0032_assign_h_loginid'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.IntegerField(default=0),
        ),
    ]
