# Generated by Django 6.0 on 2026-01-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0033_doctor_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='availability',
            field=models.IntegerField(default=0),
        ),
    ]
