# Generated by Django 6.0 on 2026-01-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaAIapp', '0034_ambulance_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.IntegerField(default=0)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DermaAIapp.doctor')),
            ],
        ),
    ]
